/*
 * Copyright (c) 2011 Google Inc.
 *
 * All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License v1.0 which accompanies this distribution, and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.google.eclipse.protobuf.ui.preferences.general;

import com.google.eclipse.protobuf.ui.preferences.PreferenceAndPropertyPage;

import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.*;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;

/**
 * @author alruiz@google.com (Alex Ruiz)
 */
public class GeneralSettingsPreferencePage extends PreferenceAndPropertyPage {
  public GeneralSettingsPreferencePage() {
  }

  private static final String PREFERENCE_PAGE_ID = GeneralSettingsPreferencePage.class.getName();
  
  /** {@inheritDoc} */
  @Override protected Control createContents(Composite parent) {
    // generated by WindowBuilder
    Composite contents = super.contentsComposite(parent);
    GridLayout gridLayout = (GridLayout) contents.getLayout();
    gridLayout.numColumns = 2;
   
    Group grpValidation = new Group(contents, SWT.NONE);
    grpValidation.setLayout(new GridLayout(1, false));
    grpValidation.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false, 2, 1));
    grpValidation.setText("Content Validation");
    
    Button btnValidateOnActivation = new Button(grpValidation, SWT.CHECK);
    btnValidateOnActivation.setText("Validate files when activated");
    return contents;
  }

  /** {@inheritDoc} */
  @Override protected void onProjectSettingsActivation(boolean active) {}

  /** {@inheritDoc} */
  @Override protected String preferencePageId() {
    return PREFERENCE_PAGE_ID;
  }

  /** {@inheritDoc} */
  @Override protected void savePreferences(IPreferenceStore store) {}

  /** {@inheritDoc} */
  @Override protected void performDefaults(IPreferenceStore store) {}
}
