/*
 * Copyright (c) 2011 Google Inc.
 *
 * All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License v1.0 which accompanies this distribution, and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.google.eclipse.protobuf.ui.preferences.pages.general;

import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

import com.google.eclipse.protobuf.ui.preferences.BooleanPreference;
import com.google.eclipse.protobuf.ui.preferences.binding.PreferenceBinder;
import com.google.eclipse.protobuf.ui.preferences.pages.PreferenceAndPropertyPage;

/**
 * @author alruiz@google.com (Alex Ruiz)
 */
public class GeneralSettingsPreferencePage extends PreferenceAndPropertyPage {

  private static final String PREFERENCE_PAGE_ID = GeneralSettingsPreferencePage.class.getName();

  /** {@inheritDoc} */
  @Override protected void doCreateContents(Composite contents) {
    // generated by WindowBuilder
    Group grpValidation = new Group(contents, SWT.NONE);
    grpValidation.setLayout(new GridLayout(1, false));
    grpValidation.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false, 3, 1));
    grpValidation.setText("Content Validation");

    Button btnValidateOnActivation = new Button(grpValidation, SWT.CHECK);
    btnValidateOnActivation.setText("Validate files when activated");
  }

  /** {@inheritDoc} */
  @Override protected BooleanPreference enableProjectSettingsPreference(IPreferenceStore store) {
    return null;
  }

  /** {@inheritDoc} */
  @Override protected void setupBinding(PreferenceBinder preferenceBinder) {}

  /** {@inheritDoc} */
  @Override protected void onProjectSettingsActivation(boolean active) {}

  /** {@inheritDoc} */
  @Override protected String preferencePageId() {
    return PREFERENCE_PAGE_ID;
  }
}
