/*
 * Copyright (c) 2011 Google Inc.
 *
 * All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License v1.0 which accompanies this distribution, and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.google.eclipse.protobuf.ui.preferences.paths;

import static com.google.eclipse.protobuf.ui.preferences.paths.Messages.*;
import static com.google.eclipse.protobuf.ui.preferences.paths.PathsPreferenceNames.*;
import static java.util.Arrays.asList;
import static org.eclipse.xtext.util.Strings.*;

import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionAdapter;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.*;
import org.eclipse.xtext.ui.editor.preferences.IPreferenceStoreAccess;

import com.google.eclipse.protobuf.ui.preferences.PreferenceAndPropertyPage;
import com.google.eclipse.protobuf.ui.swt.EventListeners;
import com.google.inject.Inject;

/**
 * Preference page for import paths.
 *
 * @author alruiz@google.com (Alex Ruiz)
 */
public class PathsPreferencePage extends PreferenceAndPropertyPage {

  private static final String COMMA_DELIMITER = ",";
  private static final String PREFERENCE_PAGE_ID = PathsPreferencePage.class.getName();

  private Group grpResolutionOfImported;
  private Button btnOneFolderOnly;
  private Button btnMultipleFolders;
  private DirectoryNamesEditor directoryNamesEditor;

  @Inject private EventListeners eventListeners;

  @Inject public PathsPreferencePage(IPreferenceStoreAccess preferenceStoreAccess) {
    super(preferenceStoreAccess);
  }

  /** {@inheritDoc} */
  @Override protected Control createContents(Composite parent) {
    // generated by WindowBuilder
    Composite contents = contentsComposite(parent);

    grpResolutionOfImported = new Group(contents, SWT.NONE);
    grpResolutionOfImported.setLayout(new GridLayout(1, false));
    grpResolutionOfImported.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false, 2, 1));
    grpResolutionOfImported.setText(importedFilesPathResolution);

    btnOneFolderOnly = new Button(grpResolutionOfImported, SWT.RADIO);
    btnOneFolderOnly.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, true, false, 1, 1));
    btnOneFolderOnly.setText(filesInOneDirectoryOnly);

    btnMultipleFolders = new Button(grpResolutionOfImported, SWT.RADIO);
    btnMultipleFolders.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, true, false, 1, 1));
    btnMultipleFolders.setText(filesInMultipleDirectories);

    directoryNamesEditor = new DirectoryNamesEditor(grpResolutionOfImported, eventListeners);
    directoryNamesEditor.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, false, false, 1, 1));
    new Label(contents, SWT.NONE);

    updateFromPreferenceStore();
    addEventListeners();

    return contents;
  }

  private void updateFromPreferenceStore() {
    IPreferenceStore store = doGetPreferenceStore();
    btnOneFolderOnly.setSelection(store.getBoolean(FILES_IN_ONE_DIRECTORY_ONLY));
    btnMultipleFolders.setSelection(store.getBoolean(FILES_IN_MULTIPLE_DIRECTORIES));
    setDirectoryNames(store.getString(DIRECTORY_NAMES));
    boolean shouldEnablePathsOptions = true;
    if (isPropertyPage()) {
      boolean useProjectSettings = store.getBoolean(ENABLE_PROJECT_SETTINGS);
      activateProjectSettings(useProjectSettings);
      shouldEnablePathsOptions = shouldEnablePathsOptions & useProjectSettings;
    }
    enableProjectOptions(shouldEnablePathsOptions);
  }

  private void addEventListeners() {
    eventListeners.addSelectionListener(new SelectionAdapter() {
      @Override public void widgetSelected(SelectionEvent e) {
        boolean selected = btnMultipleFolders.getSelection();
        directoryNamesEditor.setEnabled(selected);
        checkState();
      }
    }, asList(btnOneFolderOnly, btnMultipleFolders));
    directoryNamesEditor.onAddOrRemove(new SelectionAdapter() {
      @Override public void widgetSelected(SelectionEvent e) {
        checkState();
      }
    });
  }

  private void checkState() {
    if (directoryNamesEditor.isEnabled() && directoryNamesEditor.directoryPaths().isEmpty()) {
      pageIsNowInvalid(errorNoDirectoryNames);
      return;
    }
    pageIsNowValid();
  }

  /** {@inheritDoc} */
  @Override protected void onProjectSettingsActivation(boolean active) {
    enableProjectOptions(active);
  }

  @Override protected void performDefaults() {
    IPreferenceStore store = doGetPreferenceStore();
    btnOneFolderOnly.setSelection(store.getDefaultBoolean(FILES_IN_ONE_DIRECTORY_ONLY));
    btnMultipleFolders.setSelection(store.getDefaultBoolean(FILES_IN_MULTIPLE_DIRECTORIES));
    setDirectoryNames(store.getDefaultString(DIRECTORY_NAMES));
    boolean shouldEnablePathsOptions = true;
    if (isPropertyPage()) {
      boolean useProjectSettings = store.getDefaultBoolean(ENABLE_PROJECT_SETTINGS);
      activateProjectSettings(useProjectSettings);
      shouldEnablePathsOptions = shouldEnablePathsOptions & useProjectSettings;
    }
    enableProjectOptions(shouldEnablePathsOptions);
    super.performDefaults();
  }

  private void setDirectoryNames(String directoryNames) {
    directoryNamesEditor.addDirectoryPaths(split(directoryNames, COMMA_DELIMITER));
  }

  private void enableProjectOptions(boolean enabled) {
    grpResolutionOfImported.setEnabled(enabled);
    btnOneFolderOnly.setEnabled(enabled);
    btnMultipleFolders.setEnabled(enabled);
    directoryNamesEditor.setEnabled(btnMultipleFolders.getSelection() && enabled);
  }

  /** {@inheritDoc} */
  @Override protected void savePreferences() {
    IPreferenceStore store = getPreferenceStore();
    if (isPropertyPage()) store.setValue(ENABLE_PROJECT_SETTINGS, areProjectSettingsActive());
    store.setValue(FILES_IN_ONE_DIRECTORY_ONLY, btnOneFolderOnly.getSelection());
    store.setValue(FILES_IN_MULTIPLE_DIRECTORIES, btnMultipleFolders.getSelection());
    store.setValue(DIRECTORY_NAMES, directoryNames());
  }

  private String directoryNames() {
    return concat(COMMA_DELIMITER, directoryNamesEditor.directoryPaths());
  }

  /** {@inheritDoc} */
  @Override protected String preferencePageId() {
    return PREFERENCE_PAGE_ID;
  }
}
