/*
 * Copyright (c) 2011 Google Inc.
 *
 * All rights reserved. This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License v1.0 which accompanies this distribution, and is available at
 *
 * http://www.eclipse.org/legal/epl-v10.html
 */
package com.google.eclipse.protobuf.ui.preferences.paths;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.*;
import org.eclipse.xtext.ui.editor.preferences.IPreferenceStoreAccess;

import com.google.eclipse.protobuf.ui.preferences.PreferenceAndPropertyPage;
import com.google.inject.Inject;

/**
 * @author alruiz@google.com (Alex Ruiz)
 *
 */
public class PreferencePage extends PreferenceAndPropertyPage {

  private static final String PREFERENCE_PAGE_ID = PreferencePage.class.getName();

  private Group grpResolutionOfImported;
  private Button btnOneFolderFor;
  private Button btnLookForImported;
  private Text txtFolderNames;

  @Inject public PreferencePage(IPreferenceStoreAccess preferenceStoreAccess) {
    super(preferenceStoreAccess);
  }

  /** {@inheritDoc} */
  @Override protected Control createContents(Composite parent) {
    // generated by WindowBuilder
    Composite contents = contentsComposite(parent);
    
    grpResolutionOfImported = new Group(contents, SWT.NONE);
    grpResolutionOfImported.setLayout(new GridLayout(1, false));
    grpResolutionOfImported.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false, 2, 1));
    grpResolutionOfImported.setText("Resolution of imported files");
    
    btnOneFolderFor = new Button(grpResolutionOfImported, SWT.RADIO);
    btnOneFolderFor.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, true, false, 1, 1));
    btnOneFolderFor.setText("One folder for all .proto files");
    
    btnLookForImported = new Button(grpResolutionOfImported, SWT.RADIO);
    btnLookForImported.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, true, false, 1, 1));
    btnLookForImported.setText("Look for imported files in folders:");
    
    txtFolderNames = new Text(grpResolutionOfImported, SWT.BORDER);
    txtFolderNames.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false, 1, 1));
    new Label(contents, SWT.NONE);
    return contents;
  }

  /** {@inheritDoc} */
  @Override protected void onProjectSettingsActivation(boolean active) {
    // TODO Auto-generated method stub

  }

  /** {@inheritDoc} */
  @Override protected String preferencePageId() {
    return PREFERENCE_PAGE_ID;
  }

  /** {@inheritDoc} */
  @Override protected void savePreferences() {
    // TODO Auto-generated method stub
    
  }

}
